// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  angular.module("betterr.editor", ["ngRoute"]).config([
    "$routeProvider", "$compileProvider", function($routeProvider, $compileProvider) {
      $routeProvider.when("/editor", {
        templateUrl: "editor/editor.html",
        controller: "editorCtrl"
      });
      return $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|javascript):/);
    }
  ]).controller("editorCtrl", [
    "$scope", "$http", function($scope, $http) {
      var compile;
      compile = function(data) {
        var ast, cf_setting, compiled, jshead, result, stream, uglified;
        cf_setting = {
          bare: false,
          'no-header': true
        };
        compiled = CoffeeScript.compile(data, cf_setting);
        ast = UglifyJS.parse(compiled);
        stream = UglifyJS.OutputStream();
        ast.print(stream);
        uglified = stream.toString();
        jshead = "javascript: ";
        result = jshead.concat(uglified);
        return $scope.coffee = result;
      };
      return $http.get("editor/default.coffee").success(function(data, status, headers, config) {
        return compile(data);
      }).error(function(data, status, headers, config) {
        return console.log(data);
      });
    }
  ]);

}).call(this);
