// Generated by CoffeeScript 1.9.3
(function() {
  (function() {
    var s;
    s = document.getElementById("tongwenlet_tw2");
    if (s != null) {
      document.body.removeChild(s);
    }
    s = document.createElement("script");
    s.language = "javascript";
    s.type = "text/javascript";
    s.src = "//tongwen.openfoundry.org/NewTongWen/tools/bookmarklet_tw2.js";
    s.id = "tongwenlet_tw2";
    document.body.appendChild(s);
  })();

}).call(this);

//# sourceMappingURL=s2t.js.map
