// Generated by CoffeeScript 1.8.0
(function() {
  var compiled, setting, source;

  source = 'console.log "hellp"';

  setting = {
    bare: true,
    'no-header': true
  };

  compiled = CoffeeScript.compile(source, setting);

  $http.post('http://closure-compiler.appspot.com/compile', {
    compilation_level: 'SIMPLE_OPTIMIZATIONS',
    output_format: 'text',
    output_info: 'compiled_code',
    js_code: js
  }, function(compiled) {
    return console.log(compiled);
  });

}).call(this);
