// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  angular.module("betterr", ["ngRoute", "betterr.editor", "myApp.version"]).config([
    "$routeProvider", function($routeProvider) {
      return $routeProvider.otherwise({
        redirectTo: "/view1"
      });
    }
  ]);

}).call(this);
